# Generated by Django 3.1.3 on 2020-11-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20201022_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.appliance')),
                ('state', models.BooleanField(default=False, verbose_name='state')),
            ],
            options={
                'verbose_name': 'Socket',
                'verbose_name_plural': 'Sockets',
            },
            bases=('home.appliance',),
        ),
    ]
