name: Backend

on: [push, pull_request]

defaults:
    run:
        working-directory: backend

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Setup poetry
              uses: dschep/install-poetry-action@v1.3

            - name: Install requirements
              run: poetry install

            - name: Run flake8 checks
              run: ./test.sh flake8

            - name: Run isort
              run: ./test.sh isort

            - name: Run tests
              run: ./test.sh unittests
