name: Frontend

on: [push, pull_request]

defaults:
    run:
        working-directory: frontend

jobs:
    eslint:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install modules
              run: yarn

            - name: Run ESLint
              run: yarn run lint:js

            - name: Run stylelint
              run: yarn run lint:css

            - name: Run jest
              run: yarn run test -- --coverage --updateSnapshot

            - name: Run prettier
              run: yarn run prettier
