name: Frontend

on: [push, pull_request]

defaults:
	run:
		working-directory: frontend

jobs:
	eslint:
		name: ESLint
		runs-on: ubuntu-latest

		steps:
			- uses: actions/checkout@v2

			- name: Install modules
			run: yarn

			- name: Run ESLint
			run: yarn run eslint:github-action
