name: Lint

on: [push, pull_request]

defaults:
  run:
    working-directory: frontend

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn run eslint:github-action
