name: Lint

on: [push, pull_request_target]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        run: cp frontend/package.json . 
        
      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
